config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'posts/nagasaki' => 'posts#nagasaki'
  get 'posts/miyazaki' => 'posts#miyazaki'
  get 'posts/kumamoto' => 'posts#kumamoto'
  get 'posts/saga' => 'posts#saga'
  get 'posts/kagosima' => 'posts#kagosima'
  get 'posts/fukuoka' => 'posts#fukuoka'
  get 'posts/oita' => 'posts#oita'
  resources :posts
  root 'posts#index'
  resources :perfumes



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/perfume.rb
class Perfume < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/perfumes_controller.rb
class PerfumesController < ApplicationController
    def index
    end
  
    def new
      @perfume = Perfume.new
    end
  
    def show
      @perfume = Perfume.find_by(id: params[:id])
    end
  
    def create
      @perfume = Perfume.new(perfume_params)
      params[:perfume][:question] ? @perfume.question = params[:perfume][:question].join("") : false
      if @perfume.save
          flash[:notice] = "診断が完了しました"
          redirect_to perfume_path(@perfume.id)
      else
          redirect_to :action => "new"
      end
    end
  
  private
    def perfume_params
        params.require(:perfume).permit(:id, question: [])
    end
  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
        @posts = Post.all
    end

    def new
        @posts = Post.new
      end
    
      def create
        post = Post.new(post_params)
        if post.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
    
      def nagasaki
      end
      def miyazaki
      end
      def kumamoto
      end
      def saga
      end
      def kagosima
      end
      def fukuoka
      end
      def oita
      end
      
      private
      def post_params
        params.require(:tweet).permit(:name, :area, :address, :about, :image)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/perfumes_helper.rb
module PerfumesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nana</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <%= link_to "長崎の観光一覧へ", posts_nagasaki_path %>
<%= link_to "宮崎の観光一覧へ", posts_miyazaki_path %>
<%= link_to "大分の観光一覧へ", posts_oita_path %>
<%= link_to "福岡の観光一覧へ", posts_fukuoka_path %>
<%= link_to "佐賀の観光一覧へ", posts_saga_path %>
<%= link_to "熊本の観光一覧へ", posts_kumamoto_path %>
<%= link_to "鹿児島の観光一覧へ", posts_kagosima_path %>

<%= link_to "診断", perfumes_path %>
  </header>
  <main>
  
    <%= yield %>
  </main>
  </body>
</html>

app/views/perfumes/index.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
    <head><!--ページに表示されない情報(サイトの裏側の設定)-->
        <meta charset="utf-8">
        <title>旅行先診断スタート</title><!--ブラウザのタブのタイトルを指定-->
    </head>

    <body>
        <header>
            <h1 class="headline">
            <a>Perfu_me</a>
            </h1>
            <ul class="nav-list">
                <li class="nav-list-item">about fragrance</li>
                <li class="nav-list-item"><%= link_to "診断", perfumes_path, class: "link" %></li>
            </ul>
        </header>

        <div class="start">
            <h6>Are you ready?</h6>
            <%= link_to "診断を始める", new_perfume_path, class: "link" %>
        </div>
    </body>

app/views/perfumes/new.html.erb
<div class="abokado">

  <div class="absolute_test2">
  <br>
   <h1>おすすめ診断</h1>
   <%= form_for(@perfume, class: 'form-horizontal', role: 'form') do |f| %>
   <div class="container-sindan">
   <br>
   <br>
    <div class="row">
        <div class="col-12">
                <p>Question1. この中で旅行をする際に一番行きたい場所はどこですか</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>動物園</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>水族館</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "3", nil %>自然・植物園</p>
            </div>
            <div class="col-12">
                <p>Question2. この中で旅行をする際に一番行きたい場所はどこですか</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>温泉</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>ショッピング</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "3", nil %>神社・寺</p>
            </div>
            <div class="col-12">
                <p>Question3. この中で旅行をする際に一番行きたい場所はどこですか</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>テーマパーク</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>自然絶景スポット</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "3", nil %>歴史建造物</p>
            </div>
        </div>
    </div>
    <div class="sindanbotan">
        <%= f.submit "post" %>
    </div>
<% end %>





app/views/perfumes/show.html.erb
<div class="intoro">
<h5>診断結果</h5>
<p>あなたにおすすめの旅行先は…</p>
</div>
<div class="tweet-container">
  <div class="tweet">
    <div class="prefecture">
      <% if @perfume.question == "111" %>
      <h6>大分県</h6>

      <p>動物園：</p>
      <p>温泉：</p>
      <p>テーマパーク：</p>
      <%= link_to "大分県", posts_oita_path %>
    </div>


    <% elsif @perfume.question == "112" %>
    <h6>熊本県</h6>
    <p>動物園：</p>
    <p>温泉：</p>
    <p>自然絶景スポット：</p>
    <%= link_to "熊本県", posts_kumamoto_path %>

    <% elsif @perfume.question == "113" %>
    <h6>熊本県</h6>
    <p>動物園：</p>
    <p>温泉</p>
    <p>歴史建造物</p>
    <%= link_to "熊本県", posts_kumamoto_path %>

    <% elsif @perfume.question == "211" %>
    <h6>大分県</h6>
    <p>水族館：</p>
    <p>温泉</p>
    <p>テーマパーク</p>
    <%= link_to "大分県", posts_oita_path %>

    <% elsif @perfume.question == "212" %>
    <h6>鹿児島県</h6>
    <p>水族館：</p>
    <p>温泉：</p>
    <p>自然絶景スポット：</p>
    <%= link_to "鹿児島県", posts_kagosima_path %>

    <% elsif @perfume.question == "213" %>
    <h6>長崎県</h6>
    <p>水族館：</p>
    <p>温泉：</p>
    <p>歴史建造物：</p>
    <%= link_to "長崎県", posts_nagasaki_path %>

    <% elsif @perfume.question == "311" %>
    <h6>熊本県</h6>
    <p>自然・植物園：</p>
    <p>温泉：</p>
    <p>テーマパーク：</p>
    <%= link_to "熊本県", posts_kummoto_path %>

    <% elsif @perfume.question == "312" %>
    <h6>熊本県</h6>
    <p>自然・植物園：</p>
    <p>温泉</p>
    <p>自然絶景スポット：</p>
    <%= link_to "熊本県", posts_kumamoto_path %>

    <% elsif @perfume.question == "313" %>
    <h6>佐賀県</h6>
    <p>自然・植物園：</p>
    <p>温泉：</p>
    <p>歴史建造物：</p>
    <%= link_to "佐賀県", posts_saga_path %>

    <% elsif @perfume.question == "121" %>
    <h6>大分県</h6>
    <p>動物園：</p>
    <p>ショッピング：</p>
    <p>テーマパーク</p>
    <%= link_to "大分県", posts_oita_path %>

    <% elsif @perfume.question == "122" %>
    <h6></h6>大分県
    <p>動物園：</p>
    <p></p>ショッピング：
    <p>自然絶景スポット：</p>
    <%= link_to "大分県", posts_oita_path %>

    <% elsif @perfume.question == "123" %>
    <h6>大分県</h6>
    <p>動物園：</p>
    <p>ショッピング</p>
    <p>歴史建造物：</p>
    <%= link_to "大分県", posts_oita_path %>

    <% elsif @perfume.question == "221" %>
    <h6>大分県</h6>
    <p>水族館：</p>
    <p>ショッピング：</p>
    <p>テーマパーク：</p>
    <%= link_to "大分県", posts_oita_path %>

    <% elsif @perfume.question == "222" %>
    <h6>大分県</h6>
    <p>水族館：</p>
    <p>ショッピング：</p>
    <p>自然絶景スポット</p>
    <%= link_to "大分県", posts_oita_path %>

    <% elsif @perfume.question == "223" %>
    <h6>大分県</h6>
    <p>水族館：</p>
    <p>ショッピング</p>
    <p>歴史建造物：</p>
    <%= link_to "大分県", posts_oita_path %>

    <% elsif @perfume.question == "321" %>
    <h6>大分県</h6>
    <p>自然・植物園：</p>
    <p>ショッピング：</p>
    <p>テーマパーク：</p>
    <%= link_to "大分県", posts_oita_path %>

    <% elsif @perfume.question == "322" %>
    <h6>大分県</h6>
    <p>自然・植物園：</p>
    <p>ショッピング：</p>
    <p>自然絶景スポット：</p>
    <%= link_to "大分県", posts_oita_path %>

    <% elsif @perfume.question == "323" %>
    <h6>大分県</h6>
    <p>自然・植物園：</p>
    <p>ショッピング：</p>
    <p>歴史建造物：</p>
    <%= link_to "大分県", posts_oita_path %>

    <% elsif @perfume.question == "131" %>
    <h6>大分県</h6>
    <p>動物園：</p>
    <p>神社・寺：</p>
    <p>テーマパーク：</p>
    <%= link_to "大分県", posts_oita_path %>

    <% elsif @perfume.question == "132" %>
    <h6>大分県</h6>
    <p>動物園：</p>
    <p>神社・寺：</p>
    <p>自然絶景スポット：</p>
    <%= link_to "大分県", posts_oita_path %>

    <% elsif @perfume.question == "133" %>
    <h6>大分県</h6>
    <p>動物園：</p>
    <p>神社・寺：</p>
    <p>歴史建造物：</p>
    <%= link_to "大分県", posts_oita_path %>

    <% elsif @perfume.question == "231" %>
    <h6>大分県</h6>
    <p>水族館：</p>
    <p>神社・寺：</p>
    <p>テーマパーク：</p>
    <%= link_to "大分県", posts_oita_path %>

    <% elsif @perfume.question == "232" %>
    <h6>大分県</h6>
    <p>水族館：</p>
    <p>神社・寺：</p>
    <p>自然絶景スポット：</p>
    <%= link_to "大分県", posts_oita_path %>

    <% elsif @perfume.question == "233" %>
    <h6>大分県</h6>
    <p>水族館：</p>
    <p>神社・寺：</p>
    <p>歴史建造物：</p>
    <%= link_to "大分県", posts_oita_path %>

    <% elsif @perfume.question == "331" %>
    <h6>大分県</h6>
    <p>自然・植物園：</p>
    <p>神社・寺：</p>
    <p>テーマパーク：</p>
    <%= link_to "大分県", posts_oita_path %>

    <% elsif @perfume.question == "332" %>
    <h6>大分県</h6>
    <p>自然・植物園：</p>
    <p>神社・寺：</p>
    <p>自然絶景スポット：</p>
    <%= link_to "大分県", posts_oita_path %>

    <% elsif @perfume.question == "333" %>
    <h6>大分県</h6>
    <p>自然・植物園：</p>
    <p>神社・寺：</p>
    <p>歴史建造物：</p>
    <%= link_to "大分県", posts_oita_path %>




    <% end %>

</div>

app/views/posts/fukuoka.html.erb
<link rel="stylesheet" type="text/css" href="stylesheets/fukuoka.scss">
    <div class="headerimage-furape1">
    </div>
      <main>
        <h1 class="bigheader-furape1">
            ながさき<br/></h1>
    <h2 class="header-vanila1">バニラクリームフラペチーノ</h2>
    <div class="vanila-top1">
        <div class="vanila-11">
        <img src="itosima.jpg">
            <h3 class="sitanisuru1"><br/>チョコを感じたい方！</h3>
            <p class="setumei1">チョコレートチップ追加<br/>チョコレートソース追加</p>
        </div>
        <div class="vanila-21">
            <h3 class="sitanisuru1"><br/>甘いものでリラックスしたい方！</h3>
            <p class="setumei1">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
        </div>
         <div class="vanila-31">
            <h3 class="sitanisuru1"><br/>ショットを追加して大人に！！</h3>
            <p class="setumei1">エスプレッソショット追加<br/>キャラメルソーストッピング</p>
        </div>
     </div>
        <h2 class="header-maccha1">抹茶クリームフラペチーノ</h2>
    <div class="maccha-top1">
        <div class="maccha-11">
        　　<h3 class="sitanisuru1"><br/>抹茶とホワイトチョコの組み合わせ！</h3>
            <p class="setumei1">ホワイトモカシロップ変更<br/>抹茶パウダー増量<br/>チョコレートソース追加</p>
        </div>
        <div class="maccha-21">
        　　<h3 class="sitanisuru1"><br/>甘いものでリラックスしたい方！</h3>
        　　<p class="setumei1">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
    　　</div>
        <div class="maccha-31">
        　　<h3 class="sitanisuru1"><br/>甘いものでリラックスしたい方！</h3>
            <p class="setumei1">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
        </div>
         </div>
         <h2 class="header-choco1">ダークモカチップフラペチーノ</h2>
         <div class="choco-top1">
             <div class="choco-11">
                <h3 class="sitanisuru1"><br/>甘いものでリラックスしたい方！</h3>
                <p class="setumei1">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
            </div>
             <div class="choco-21">
                <h3 class="sitanisuru1"><br/>甘いものでリラックスしたい方！</h3>
                <p class="setumei1">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
            </div>
             <div class="choco-31">
                <h3 class="sitanisuru1"><br/>甘いものでリラックスしたい方！</h3>
                <p class="setumei1">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
            </div>
              </div>
             

app/views/posts/index.html.erb
<div class="zentai">


<h1>自分の題名</h1>
<h3>一覧ページ</h3>

</div>

app/views/posts/kagosima.html.erb
<link rel="stylesheet" type="text/css" href="stylesheets/kagosima.scss">
    <div class="headerimage-furape">
    </div>
      <main>
        <h1 class="bigheader-furape">
            ながさき<br/></h1>
    <h2 class="header-vanila">バニラクリームフラペチーノ</h2>
    <div class="vanila-top">
        <div class="vanila-1">
        <img src="itosima.jpg">
            <h3 class="sitanisuru"><br/>チョコを感じたい方！</h3>
            <p class="setumei">チョコレートチップ追加<br/>チョコレートソース追加</p>
        </div>
        <div class="vanila-2">
            <h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
            <p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
        </div>
         <div class="vanila-3">
            <h3 class="sitanisuru"><br/>ショットを追加して大人に！！</h3>
            <p class="setumei">エスプレッソショット追加<br/>キャラメルソーストッピング</p>
        </div>
     </div>
        <h2 class="header-maccha">抹茶クリームフラペチーノ</h2>
    <div class="maccha-top">
        <div class="maccha-1">
        　　<h3 class="sitanisuru"><br/>抹茶とホワイトチョコの組み合わせ！</h3>
            <p class="setumei">ホワイトモカシロップ変更<br/>抹茶パウダー増量<br/>チョコレートソース追加</p>
        </div>
        <div class="maccha-2">
        　　<h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
        　　<p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
    　　</div>
        <div class="maccha-3">
        　　<h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
            <p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
        </div>
         </div>
         <h2 class="header-choco">ダークモカチップフラペチーノ</h2>
         <div class="choco-top">
             <div class="choco-1">
                <h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
                <p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
            </div>
             <div class="choco-2">
                <h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
                <p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
            </div>
             <div class="choco-3">
                <h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
                <p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
            </div>
              </div>

app/views/posts/kumamoto.html.erb
<link rel="stylesheet" type="text/css" href="stylesheets/kumamoto.scss">
<div class="headerimage-furape">
</div>
  <main>
    <h1 class="bigheader-furape">
        ながさき<br/></h1>
<h2 class="header-vanila">バニラクリームフラペチーノ</h2>
<div class="vanila-top">
    <div class="vanila-1">
    <img src="itosima.jpg">
        <h3 class="sitanisuru"><br/>チョコを感じたい方！</h3>
        <p class="setumei">チョコレートチップ追加<br/>チョコレートソース追加</p>
    </div>
    <div class="vanila-2">
        <h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
        <p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
    </div>
     <div class="vanila-3">
        <h3 class="sitanisuru"><br/>ショットを追加して大人に！！</h3>
        <p class="setumei">エスプレッソショット追加<br/>キャラメルソーストッピング</p>
    </div>
 </div>
    <h2 class="header-maccha">抹茶クリームフラペチーノ</h2>
<div class="maccha-top">
    <div class="maccha-1">
    　　<h3 class="sitanisuru"><br/>抹茶とホワイトチョコの組み合わせ！</h3>
        <p class="setumei">ホワイトモカシロップ変更<br/>抹茶パウダー増量<br/>チョコレートソース追加</p>
    </div>
    <div class="maccha-2">
    　　<h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
    　　<p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
　　</div>
    <div class="maccha-3">
    　　<h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
        <p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
    </div>
     </div>
     <h2 class="header-choco">ダークモカチップフラペチーノ</h2>
     <div class="choco-top">
         <div class="choco-1">
            <h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
            <p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
        </div>
         <div class="choco-2">
            <h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
            <p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
        </div>
         <div class="choco-3">
            <h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
            <p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
        </div>
          </div>

app/views/posts/miyazaki.html.erb
<link rel="stylesheet" type="text/css" href="stylesheets/miyazaki.scss">

<div class="headerimage-furape">
</div>
  <main>
    <h1 class="bigheader-furape">
        ながさき<br/></h1>
<h2 class="header-vanila">バニラクリームフラペチーノ</h2>
<div class="vanila-top">
    <div class="vanila-1">
    <img src="itosima.jpg">
        <h3 class="sitanisuru"><br/>チョコを感じたい方！</h3>
        <p class="setumei">チョコレートチップ追加<br/>チョコレートソース追加</p>
    </div>
    <div class="vanila-2">
        <h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
        <p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
    </div>
     <div class="vanila-3">
        <h3 class="sitanisuru"><br/>ショットを追加して大人に！！</h3>
        <p class="setumei">エスプレッソショット追加<br/>キャラメルソーストッピング</p>
    </div>
 </div>
    <h2 class="header-maccha">抹茶クリームフラペチーノ</h2>
<div class="maccha-top">
    <div class="maccha-1">
    　　<h3 class="sitanisuru"><br/>抹茶とホワイトチョコの組み合わせ！</h3>
        <p class="setumei">ホワイトモカシロップ変更<br/>抹茶パウダー増量<br/>チョコレートソース追加</p>
    </div>
    <div class="maccha-2">
    　　<h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
    　　<p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
　　</div>
    <div class="maccha-3">
    　　<h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
        <p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
    </div>
     </div>
     <h2 class="header-choco">ダークモカチップフラペチーノ</h2>
     <div class="choco-top">
         <div class="choco-1">
            <h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
            <p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
        </div>
         <div class="choco-2">
            <h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
            <p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
        </div>
         <div class="choco-3">
            <h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
            <p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
        </div>
          </div>

app/views/posts/nagasaki.html.erb
<link rel="stylesheet" type="text/css" href="stylesheets/nagasaki.scss">
<div class="headerimage-furape">
</div>
  <main>
    <h1 class="bigheader-furape">
        ながさき<br/></h1>
<h2 class="header-vanila">バニラクリームフラペチーノ</h2>
<div class="vanila-top">
    <div class="vanila-1">
    <img src="itosima.jpg">
        <h3 class="sitanisuru"><br/>チョコを感じたい方！</h3>
        <p class="setumei">チョコレートチップ追加<br/>チョコレートソース追加</p>
    </div>
    <div class="vanila-2">
        <h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
        <p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
    </div>
     <div class="vanila-3">
        <h3 class="sitanisuru"><br/>ショットを追加して大人に！！</h3>
        <p class="setumei">エスプレッソショット追加<br/>キャラメルソーストッピング</p>
    </div>
 </div>
    <h2 class="header-maccha">抹茶クリームフラペチーノ</h2>
<div class="maccha-top">
    <div class="maccha-1">
    　　<h3 class="sitanisuru"><br/>抹茶とホワイトチョコの組み合わせ！</h3>
        <p class="setumei">ホワイトモカシロップ変更<br/>抹茶パウダー増量<br/>チョコレートソース追加</p>
    </div>
    <div class="maccha-2">
    　　<h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
    　　<p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
　　</div>
    <div class="maccha-3">
    　　<h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
        <p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
    </div>
     </div>
     <h2 class="header-choco">ダークモカチップフラペチーノ</h2>
     <div class="choco-top">
         <div class="choco-1">
            <h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
            <p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
        </div>
         <div class="choco-2">
            <h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
            <p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
        </div>
         <div class="choco-3">
            <h3 class="sitanisuru"><br/>甘いものでリラックスしたい方！</h3>
            <p class="setumei">ホワイトモカシロップ変更<br/>蜂蜜蜂蜜トッピング</p>
        </div>
          </div>